---
- name: pcs | add redis user to haclient group
  user:
    name: redis
    group: redis
    shell: /usr/sbin/nologin
    groups:
      - redis
      - haclient
    append: no

- name: pcs | pacemaker redis acls
  command: "{{ item }}"
  register: pcs_out
  changed_when: pcs_out.rc == 0
  failed_when: "pcs_out.rc != 0 and pcs_out.stderr.find('already exists') == -1"
  with_items:
    - pcs acl enable
    - pcs acl role create RedisRole description="Full access to cluster" write xpath /cib
    - pcs acl user create redis RedisRole
  when: inventory_hostname == play_hosts[0]
