---
- name: pacemaker | network
  import_tasks: network.yml
  tags:
    - redis-pacemaker-network

- name: pacemaker | acl
  import_tasks: acl.yml
  tags:
    - redis-pacemaker-acl

- name: pacemaker | helpers
  import_tasks: helpers.yml
  tags:
    - redis-pacemaker-helpers

- name: pacemaker | systemd
  import_tasks: systemd.yml
  tags:
    - redis-pacemaker-systemd

- name: pacemaker | resources reset
  import_tasks: resources-reset.yml
  become_user: redis
  become: yes
  tags:
    - redis-pacemaker-resources-reset
  when: inventory_hostname == play_hosts[0] and redis_pacemaker_reset|bool

- name: pacemaker | resources
  import_tasks: resources.yml
  become_user: redis
  become: yes
  tags:
    - redis-pacemaker-resources
  when: inventory_hostname == play_hosts[0]

- name: pacemaker | resources reset
  import_tasks: helpers-init.yml
  become_user: redis
  become: yes
  tags:
    - redis-pacemaker-helpers-init
  when: redis_pacemaker_helpers_init|bool
