---
- name: resources reset | pcs cleanup
  command: "{{ item }}"
  register: pcs_out
  changed_when: pcs_out.rc == 0
  failed_when: >-
    pcs_out.rc != 0 and 
    pcs_out.stderr.find('could not find') == -1 and
    pcs_out.stderr.find('does not exist') == -1
  with_items:
    - pcs cluster cib redis-ha
    - pcs -f redis-ha resource unclone RedisLBReadBlock-clone
    - pcs -f redis-ha resource unclone RedisLBWriteBlock-clone
    - pcs -f redis-ha resource delete RedisLBReadBlock
    - pcs -f redis-ha resource delete RedisLBWriteBlock
    - pcs cluster cib-push --wait 60 redis-ha
  args:
    chdir: /var/lib/redis
- name: pcs | pcs remove redis_role attribute from nodes
  command: "pcs node attribute {{ hostvars[item]['ansible_hostname'] }} redis_role="
  register: pcs_out
  changed_when: pcs_out.rc == 0
  failed_when: "pcs_out.rc != 0 and pcs_out.stderr.find('t exist for node') == -1"
  with_items: "{{ play_hosts }}"