---
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence  # sentinel keeps updating config
    - verify
    - destroy

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: node1
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

  - name: node2
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

  - name: node3
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        install_python3: true
        redis_password: 1q2w3e4r5t

        redis_backups: true

        # verify playbook vars
        _verify_redis_password: "{{ redis_password }}"
        _verify_redis_role:  "{{ redis_role }}"
        _verify_expected_slaves: 2
    host_vars:
      node1:
        redis_role: master
      node2:
        redis_role: slave
      node3:
        redis_role: slave
verifier:
  name: ansible
